### ISSUE TITLE
Authentication required when pulling docker.elastic.co Docker images

### ISSUE THREAD

**Issue by reupen** [elastic/elasticsearch-docker#237] opened 2019-03-22 16:42 UTC
## Bug Description

In the last half-hour or so we've been getting 'authentication required' errors when pulling official docker images from docker.elastic.co on our CI and locally.

For example:

```
$ docker pull docker.elastic.co/elasticsearch/elasticsearch:6.4.3
Error response from daemon: unauthorized: authentication required

$ docker pull docker.elastic.co/elasticsearch/elasticsearch:6.6.2
Error response from daemon: unauthorized: authentication required
```

(Apologies, as I was not sure what the best place to report this was.)

**Comment by bagbag** [comment] 2019-03-22 16:45
I can confirm that.

**Comment by jasontedor** [comment] 2019-03-22 16:46
Thanks for the report. We can reproduce this and are on it.

**Comment by bagbag** [comment] 2019-03-22 16:47
Out of curiosity: Why don't you use the offical registry?

**Comment by SmithPeder** [comment] 2019-03-22 16:59
I can confirm that too 💯

**Comment by aliciascott** [comment] 2019-03-22 17:10
Getting same problem for myself and my customer.. 

Adding note to follow this

**Comment by jankenr** [comment] 2019-03-22 17:20
Confirmed. Was already looking around for a solution...

**Comment by jasontedor** [comment] 2019-03-22 17:25
Sorry for the continued degradation folks. We are aware of the broad impact that an issue like this has. The appropriate team is focused on the issue now and is working towards a resolution. I am sorry that we do not have an ETA to offer at this time, but I hope that you can bear with us as they work through the issue.

**Comment by jasontedor** [comment] 2019-03-22 17:55
We believe that this issue is resolved now. If a few people can confirm that for us here, that would be appreciated! 🙏

**Comment by supersam654** [comment] 2019-03-22 17:56
Works for me. Thanks!

**Comment by reupen** [comment] 2019-03-22 17:57
Also working for me now. Thanks!

**Comment by jasontedor** [comment] 2019-03-22 17:59
Thanks for confirming @supersam654 and @reupen. I will close this issue as resolved. If anyone still has issues after this, please feel free to comment here and we will reopen as needed.

**Closed by jasontedor** 2019-03-22 17:59 UTC
