### ISSUE TITLE
/usr/share/elasticsearch/xpack directory exists in the 6.3 image

### ISSUE THREAD

**Issue by danleerunk** [elastic/elasticsearch-docker#177] opened 2018-07-03 22:40 UTC
* Docker image used: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
* Operating System: Mac OSX 10.13.5 (17F77)
* `docker info` output: [docker_info.txt](https://github.com/elastic/elasticsearch-docker/files/2161276/docker_info.txt)
* `docker inspect NAME|ID` output: [docker_inspect.txt](https://github.com/elastic/elasticsearch-docker/files/2161277/docker_inspect.txt)

* Steps to reproduce
1. Log in to the running container (e.g. `docker exec -it <name> /bin/bash`)
2. Browse to `/usr/share/elasticsearch/bin`
3. Note the presence not only of the relocated commands (such as `elasticsearch-certgen` etc) but also the `x-pack` directory, which contains those same utilities (sans their new `elasticsearch-` prefix).

## Bug Description

Expected behavior: the x-pack directory no longer exists in the Elasticsearch 6.3.0 image.

Issue: the x-pack directory does exist in the /usr/share/elasticsearch/bin directory in the Elasticsearch 6.3.0 image.

**Comment by xeraa** [comment] 2018-07-03 22:55
IMO this is for backwards compatibility. The components in the *x-pack* folder print a warning to switch to the ones in the base folder:

```
# /usr/share/elasticsearch/bin/x-pack/certgen
/usr/share/elasticsearch/bin/x-pack/certgen is deprecated, use /usr/share/elasticsearch/bin/elasticsearch-certgen
```

From the top of my head you get exactly the same setup with the DEB packages. Or is there another issue with this *x-pack* folder being present that I'm overlooking?

**Comment by danleerunk** [comment] 2018-07-03 23:46
Hey @xeraa, I don't believe you're missing anything. I used an rpm install as the baseline on CentOS 7.4, which no longer includes that folder, so I wanted to bring it up as potentially unnecessary duplication if it was just an oversight. If it's useful for backwards compatibility it totally makes sense to keep it around and this can be closed out.

**Comment by strawgate** [comment] 2018-07-04 03:36
@xeraa and @danleerunk -- the certgen script just walks up a directory using dirname.

This works if you call certgen with its full path, "/usr/share/elasticsearch/bin/x-pack/certgen" as walking up a directory brings us to, "/usr/share/elasticsearch/bin" where elasticsearch-certgen is appended.

The issue is if you change directory into the x-pack dir, this causes the script to look for elasticsearch-certgen in the x-pack dir: 

```
[root@e09d9cdec68f x-pack]# ./certgen
./certgen is deprecated, use ./elasticsearch-certgen
./certgen: line 13: ./elasticsearch-certgen: No such file or directory
```

It looks like in this case `dirname certgen $0` returns "." which then gets elasticsearch-certgen added to it  which results in ./elasticsearch-certgen and prints the error above breaking backwards compatiblity.

**Comment by xeraa** [comment] 2018-07-04 09:15
Ah, that is indeed an issue. But IMO not limited to the Docker images, so I've opened elastic/elasticsearch/issues/31785.

Guess we can close this one here in the meantime. Not sure if this will be fixed of if the deprecated certgen will just be removed.

**Closed by xeraa** 2018-07-04 09:15 UTC
Labels: 6.3, bug
