### ISSUE TITLE
ElasticSearch Starting with Cluster Name Mount Error

### ISSUE THREAD

**Issue by stevenmccord** [elastic/elasticsearch-docker#69] opened 2017-06-06 22:02 UTC
## Bug Description

When I run this locally I don't get this but now I am mounting a drive in a Kubernetes cluster and I am getting the following error:

```
[2017-06-06T21:32:38,666][INFO ][o.e.n.Node               ] [eazy-e-0] initializing ...
[2017-06-06T21:32:38,701][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [eazy-e-0] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: failed to obtain node locks, tried [[/usr/share/elasticsearch/data/icx-es-data]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:125) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:96) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.cli.Command.main(Command.java:62) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82) ~[elasticsearch-5.1.1.jar:5.1.1]
Caused by: java.lang.IllegalStateException: failed to obtain node locks, tried [[/usr/share/elasticsearch/data/icx-es-data]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?
	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:259) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.node.Node.<init>(Node.java:249) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.node.Node.<init>(Node.java:229) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:214) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:214) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:306) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-5.1.1.jar:5.1.1]
	... 6 more
Caused by: java.io.IOException: failed to obtain lock on /usr/share/elasticsearch/data/nodes/0
	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:238) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.node.Node.<init>(Node.java:249) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.node.Node.<init>(Node.java:229) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:214) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:214) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:306) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-5.1.1.jar:5.1.1]
	... 6 more
Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes/0/node.lock
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177) ~[?:?]
	at java.nio.channels.FileChannel.open(FileChannel.java:287) ~[?:1.8.0_92-internal]
	at java.nio.channels.FileChannel.open(FileChannel.java:335) ~[?:1.8.0_92-internal]
	at org.apache.lucene.store.NativeFSLockFactory.obtainFSLock(NativeFSLockFactory.java:113) ~[lucene-core-6.3.0.jar:6.3.0 a66a44513ee8191e25b477372094bfa846450316 - shalin - 2016-11-02 19:47:11]
	at org.apache.lucene.store.FSLockFactory.obtainLock(FSLockFactory.java:41) ~[lucene-core-6.3.0.jar:6.3.0 a66a44513ee8191e25b477372094bfa846450316 - shalin - 2016-11-02 19:47:11]
	at org.apache.lucene.store.BaseDirectory.obtainLock(BaseDirectory.java:45) ~[lucene-core-6.3.0.jar:6.3.0 a66a44513ee8191e25b477372094bfa846450316 - shalin - 2016-11-02 19:47:11]
	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:225) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.node.Node.<init>(Node.java:249) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.node.Node.<init>(Node.java:229) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:214) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:214) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:306) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-5.1.1.jar:5.1.1]
	... 6 more
```

I noticed that the cluster name is now in the mount path.  

I am utilizing the following image:

`FROM docker.elastic.co/elasticsearch/elasticsearch:5.1.1`

Maybe this is a docker version issue as well?  Thanks!

**Comment by jarpy** [comment] 2017-06-07 04:20
Hi,

Would you be able to post your pod config? I'll take a look and see if I can reproduce this on a Kubernetes cluster somewhere. Forgive me, but any support provided here will be kind of "best effort". Configuring Kubernetes (or any other orchestrator) is really out of scope for this project. It's goal is to provide an image that is complete and correct for Docker in general. But obviously, if we discover that we have a bug that genuinely breaks our ability to run under Kubernetes, we will want to fix that!

**Comment by stevenmccord** [comment] 2017-06-07 12:04
@jarpy do you mean the manifest files for the statefulset for Kuberentes?  I missed on vital piece of information here for you guys.  I was using the old official image from Dockerhub and then I switched to the new official version, and this was happening.  Interesting though, my local cluster doesn't appear to be doing this, but that might be because I didn't have data in the local cluster from the old version of docker.  I will continue to mess with this on my end to see if I can find more relevant information.

**Comment by jarpy** [comment] 2017-06-08 04:13
Thanks. To be honest, I'm not sure what exactly I mean. We're not Kubernetes users here, so I don't know all the terminology. Anything you can provide to help me reproduce the issue would be much appreciated.

It's certainly interesting that the old Docker Inc. image works, so I'm anxious to learn more.

**Comment by stevenmccord** [comment] 2017-06-08 18:56
@jarpy OK, I think I have this figured out and I was able to reproduce locally.  I don't think this is a Kubernetes issue specifically.  This is a old docker image to new docker image issue.  You can reproduce this by utilizing the old docker image `FROM elasticsearch:5.1.1` and put data into it.  I actually restored some data from this image with a mounted drive (this can be Docker compose I would imagine, but I utilize Kuberenetes to mount).  Then I change the Docker image to `FROM docker.elastic.co/elasticsearch/elasticsearch:5.1.1` with the same mount and it will blow up.  

What I have found is that it is a permissions issue, b/c in the old docker image they don't actually create the elasticsearch user, but it gets generated with a uid=105 and a gid=108.  However, in your dockerfile you set those uid and gid to 1000.  All we really need to do is loop through those directories and ensure the new user owns them.  

I created a reference PR, I didn't sign any agreeement, but I can do that if you want this into master.  

https://github.com/elastic/elasticsearch-docker/pull/70

**Comment by jarpy** [comment] 2017-06-09 01:09
Ah yes, the dreaded permissions problem! Thanks for the detailed analysis. We do take a really strong position on the user that runs the container, with not even the entrypoint running as root. It's all part of the endless security versus ease-of-use battle.

We generally [suggest](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_notes_for_production_use_and_defaults) that people ensure any location that should be written to by the container process is writable by UID 1000 on the host system itself.

**Closed** 2017-06-20 22:52 UTC

**Comment by reco77** [comment] 2018-07-09 09:57
for me it was because of my old container , i do `docker system prune` to delete un used containers
and make the container up again
