### ISSUE TITLE
Add FAQ for "y u no latest?"

### ISSUE THREAD

**Issue by drewr** [elastic/elasticsearch-docker#84] opened 2017-07-06 19:02 UTC
Probably worth adding to our readme. It's too common of a practice to be left to discovering within closed issues.

**Comment by jarpy** [comment] 2017-07-06 23:56
We could also consider adding minor version tags, like `5.4`, `5.5`, since rolling updates for those should be fairly safe.

**Comment by dliappis** [comment] 2017-07-07 08:57
One other question here is what's the right place to store this info. Is the readme.md file read that frequently anymore or should the info go to the es docs? Another approach would be to add a link for "why no latest?" in www.docker.elastic.co and present the relevant fragment from readme.md. Thoughts?

**Comment by drewr** [comment] 2017-07-08 13:48
I like the idea for minor versions :+1: 

I agree that it may be even important enough to put on our download page. As it gets integrated we should add it. For now though, the readme is a logical place so people aren't scratching their heads. We should do it in `*-docker` repos.

**Comment by xeraa** [comment] 2017-07-11 21:59
Are mixed patch level versions really a good idea? I assume we cannot ensure that people will only use it for rolling upgrades instead of creating mixed clusters for longer timeframes.

I don't see a big (enough) benefit for mixed clusters; either there is a relevant bugfix and you want to upgrade all instances or a specific version is good for all instance. But there is always a risk of version mixing; especially when there is a (patch level) Lucene upgrade.

**Comment by jarpy** [comment] 2017-07-13 03:25
I was only suggesting that we allow "rollup" for patch releases, so `5.4` would be a valid tag but `5` would not. That way, users can essentially opt in to "automatic security updates", but not "automatic feature _upgrades_".

**Comment by jarpy** [comment] 2017-07-13 03:28
Reading your post again, @xerra, I think we already agreed about the exact nature of the suggestion, but not about whether it was a good idea. Sorry for trying to clarify what was already very clear in your mind!

**Comment by xeraa** [comment] 2017-07-13 07:58
Maybe I just don't understand the use case. How would the automatic security updates work :)?

**Comment by HariSekhon** [comment] 2017-11-20 14:57
Both `latest` and `major.minor` version tags should be supported as per standard.

`latest` is legitimately used in CI tests of existing code to detect breaking updates that a developer will want to write updates for before users notice it doesn't work with the latest Elasticsearch version.

Additionally, it's standard to support `major.minor` versions which are non-breaking and can change, if people really want to fix to `x.y.z` format instead of the more convenient `x.y` format (again, especially for CI tests) then they can do that regardless.

The tags should exist as users should have the option to use them. You can discourage it in documentation and make the default documentation point to specific releases but removing the tags entirely does not seem like a good idea when there are legitimate use cases for them.

**Comment by xeraa** [comment] 2017-12-26 02:44
I guess we can agree to disagree on this one :)

1) Having `latest` just for CI is pretty much like requiring every method to be public, so you can easily unit test it. Sounds like a good, but you are trying to optimize for the wrong scenario.
2) There's a reason why dependency management systems don't support latest or removed that feature again, for example `LATEST` and `RELEASE` were removed in Maven 3 ["For the sake of reproducible builds"](https://cwiki.apache.org/confluence/display/MAVEN/Maven+3.x+Compatibility+Notes#Maven3.xCompatibilityNotes-PluginMetaversionResolution).
3) As you're saying, since you need to test "against all the `x.y` versions" anyway, you'll need to change the configuration anyhow. Instead of explicitly adding the previous version once `latest` gets updated, you'll have to add the most current version.
4) "You can discourage it in documentation" — we all know how well that works and where people will complain especially for persistent services ;)

**Comment by HariSekhon** [comment] 2017-12-26 15:16
`latest` allows CI runs to detect new versions released that break existing code and tests - this is an extremely valuable feature of Docker for automated update incompatibility detection while a developer is often aware that there is a new release upstream. This is the point of automation - to allow some things to happen automatically for convenience.

I appreciate what you're saying about fixing build numbers for reproducibility, but this isn't a code library being embedded in to a software application.

Currently the behaviour of this repo contravenes Docker standards for all the different dockerized technologies I've used from DockerHub - it doesn't really make sense to deviate from the standard and even breaks quick command line testing that Docker is known for as Docker implies `latest` by design.

**Comment by xeraa** [comment] 2017-12-27 01:07
> this isn't a code library being embedded in to a software application.

No it's worse: Rather than running into a compile- or runtime-exception you might screw up your data.

> breaks quick command line testing that Docker is known for as Docker implies `latest` by design.

If you cannot be bothered to copy the right version number from the docs, you won't have a good time with our images. This is not a stateless image that you "just run" — we really want people to read the docs and understand them.

And [quoting the Docker docs on best practices](https://docs.docker.com/develop/dev-best-practices/):

> When building images, always tag them with useful tags which codify version information, intended destination (`prod` or `test`, for instance), stability, or other information that will be useful when deploying the application in different environments. **Do not rely on the automatically-created `latest` tag.**

**Comment by HariSekhon** [comment] 2017-12-27 12:10
Your examples are also valid - if I was deploying data I wanted to keep in these docker images then fixing the version number is important, but I think the point that's being missed is that there are also testing use cases that benefit from use of ```latest``` and it would be nice to support those.

> This is not a stateless image that you "just run"

Actually in my use case I fire up Elasticsearch, load some test data and execute my code against it, and then destroy the docker container. So for all intents and purposes it is. If any of that doesn't work on the latest version I want to automatically know to provide an update before the next user to run the latest version finds out it doesn't work and complains. This is a valuable use case that is not catered to without a ```latest``` tag. Otherwise it requires a human closely tracking whenever Elastic does a release and manually test / update test versions before any user tries to use the latest version. This seems impractical, especially given the plethora of technologies I work with...

>  always tag them with useful tags which codify version information...

Yes everyone does this as well

> Do not rely on the automatically-created latest tag.

Not relying on it for prod or data, it's merely a convention of convenience provided by pretty much all dockerized applications, which does have its valid uses. I appreciate you didn't intend to cater to those uses but it would be nice if you could at least consider it.

We might have to agree to disagree on the principal of providing flexibility to users. If you really hate ```latest``` and want to be different to just about every other dockerized application out there then a ```dev``` tag or similar which is retagged to the latest release would also suffice.

**Comment by xeraa** [comment] 2017-12-27 21:03
If there is a decision between being more lenient or stricter, we have learned over the past few years that the stricter side is where we want to be at. We'd rather have a little pain upfront than big issues later on. For example Elasticsearch simply doesn't start up if:

* you try to run it as root
* there are errors or unknown commands in your config
* there are errors in the bootstrap checks and you're in production mode

And I think not having `latest` follows that approach as well. I'm sorry if that's not a good choice for your use case. Unfortunately this is a pretty binary decision; having `dev` instead would open up the same issues as `latest` with the additional overhead of more confusion and not being a convention.

Thank you for your feedback — we always try to learn from our users and will keep it in mind for the future.

PS: Actually, we had `latest` for a very short amount of time, but then realized that this wasn't the right way to go forward.

**Comment by xeraa** [comment] 2018-01-19 14:14
Relevant for the discussion about providing minor version labels (like `6.1` instead of `6.1.1`):

> helping a user decipher an ES warning: "target node version [6.1.1] is older than the source node version [6.1.2] and may not support codecs or postings formats for a newer Lucene version" -- what action should be taken by the user when they see this? The scenario (as I am told) is they were adding a new node (not sure which was the 'new' version cluster or new node -- and this came up.)

Adrien Grand:
> this is the allocation decider that explains why a shard can't be moved to a different node. The action to take is to finish the upgrade so that all nodes are on 6.1.2, this message suggests at least one node is on 6.1.1. **Elasticsearch cannot guarantee good balance of shard allocation in a cluster that has multiple versions**, this should be a transient situation.

Emphasis mine — IMO this should be the end of any minor version label discussions (also for future reference since I'm sure another issue for this will pop up at some point)

**Comment by Santinell** [comment] 2018-02-13 10:27
Just don't update Lucene version in minor versions and all will be fine.

**Comment by teohhanhui** [comment] 2019-05-07 18:32
> IMO this should be the end of any minor version label discussions

There are CI use cases where we're not running a cluster, but just want to make sure our integration works with the supported version of Elasticsearch, e.g. 6.x

**Comment by rjernst** [comment] 2019-06-26 00:27
The fact there is no `latest` tag is addressed in documentation. Additionally, maintenance of the docker files for elasticsearch has moved to the elasticsearch repo. As we will be archiving this repository, I am going to close this issue.

**Closed by rjernst** 2019-06-26 00:27 UTC
